### ISSUE TITLE
Request Azure Private Link

### ISSUE THREAD

**Issue by alvarezfr** [backstage-tutorial/testing-templates#26]
The issue created by this issue template will request a private link to an Azure resource by an automated process that will need to be completed by the team owner of the repo. Please, do not modify the skeleton of the following YAML as it will be parsed by an automated process.

#### region
Type: `string`. The possible values are:
- `weu`
- `us1`

#### environment
Type: `string`. The possible values are:
- `dev`
- `pre`
- `pro`

#### client
Type: `string`. Use the code name of your project.
Examples:
- `client1`
- `client2`
- `client3`

You can see the list of the current registered clients for the dev environment [here](https://github.com/backstage-tutorial/testing-templates/tree/main/workloads/weu/dev) to avoid creating the same client twice with different name.

##### private_endpoint_name
Type: `string`.
Set the name of your private endpoint.
Example: `pgxdweuxxxxxxxxx01`

##### private_link_name
Type: `string`.
Set the name of your private link.
Example: `pgxdweuxxxxxxxxx01`

##### private_link_id
Type: `string`.
Set the id of your private link.
Example: `/subscriptions/xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxx/resourceGroups/xxxxxxxxxxxxx/privateLinks/xxxxxxxxxxxxx`

## Configuration
**Adapt the yaml to your needs.**

```yaml
region: zu1
environment: dev
client: client3
private_endpoint_name: pgxdweuxxxxxxxxx01
private_link_name: pgxdweuxxxxxxxxx01
private_link_id: /subscriptions/xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxx/resourceGroups/xxxxxxxxxxxxx/privateLinks/xxxxxxxxxxxxx
```
