### ISSUE TITLE
Request AWS Private Link

### ISSUE THREAD

**Issue by alvarezfr** [backstage-tutorial/testing-templates#28]
The issue created by this issue template will request a private link to an AWS resource by an automated process that will need to be completed by the team owner of the repo. Please, do not modify the skeleton of the following YAML as it will be parsed by an automated process.

#### region
Type: `string`. The possible values are:
- `weu`
- `us1`

#### environment
Type: `string`. The possible values are:
- `dev`
- `pre`
- `pro`

#### client
Type: `string`. Use the code name of your project.
Examples:
- `client1`
- `client2`
- `client3`

You can see the list of the current registered clients for the dev environment [here](https://github.com/backstage-tutorial/testing-templates/tree/main/workloads/weu/dev) to avoid creating the same client twice with different name.

##### private_endpoint_service_name
Type: `string`.
Set the service name for your AWS Private Endpoint.
Example: `endpoint_id.endpoint_service_id.region.vpce.amazonaws.com`

## Configuration
**Adapt the yaml to your needs.**

```yaml
region: weu
environment: dev
client: client1
private_endpoint_service_name: endpoint_id.endpoint_service_id.region.vpce.amazonaws.com
```
